package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.nuaa.sys.util.Logger;
import com.nuaa.sys.util.AppInsFactory;
import com.nuaa.app.Login;
import com.nuaa.app.GuiStr;
import com.nuaa.app.RoleLevel;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/web/inc/jsp/head_ext.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/system/file/errorpage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write(".n{TEXT-DECORATION:none} \r\n");
      out.write("</style>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Ext -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tsms/web/inc/resources/css/ext-all.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tsms/web/inc/resources/css/add.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/adapter/ext/ext-base.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/ext-all.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/ext-cg.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/ext.search.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/calendar.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/calendar-zh.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/calendar-setup.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/ext-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/Ext.ux.ToastWindow.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/Ext.ux.InlineToolbarTabPanel.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tsms/web/inc/resources/UploadDialog/css/Ext.ux.UploadDialog.css\" />\r\n");
      out.write("<script type='text/javascript' src='/tsms/web/inc/resources/UploadDialog/Ext.ux.UploadDialog.js' ></script>\r\n");
      out.write("<script type='text/javascript' src='/tsms/web/inc/resources/UploadDialog/Ext.ux.UploadDialog.packed.js' ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/keyboard.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tsms/web/inc/resources/css/win_keyboard.css\" />\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/jquery-1.4.4.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/web/inc/resources/js/jquery.keypad.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/tsms/web/inc/resources/css/jquery.keypad.css\" />\r\n");
      out.write("\r\n");

	String rolename=(String)session.getAttribute("rolename");
	String username=(String)session.getAttribute("username");
	String userid=(String)session.getAttribute("userid");
	String userlevel=(String)session.getAttribute("userlevel");
	String multrole=(String)session.getAttribute("multrole");

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var rolename=\"");
      out.print(rolename);
      out.write("\";\r\n");
      out.write("var username=\"");
      out.print(username);
      out.write("\";\r\n");
      out.write("var userid=\"");
      out.print(userid);
      out.write("\";\r\n");
      out.write("var userlevel=\"");
      out.print(userlevel);
      out.write("\";\r\n");
      out.write("var multrole=\"");
      out.print(multrole);
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("//状态对应级别 此处配置级别\r\n");
      out.write("var RoleLevel={};//用户级别\r\n");
      out.write("RoleLevel.UserLev=1;//用户\r\n");
      out.write("RoleLevel.StoreManagerLevel=2;//库房管理员\r\n");
      out.write("RoleLevel.TeamLeaderLevel=3;//专家\r\n");
      out.write("RoleLevel.BossLevel=4;//领导\r\n");
      out.write("RoleLevel.SysLevel=5;//系统管理员\r\n");
      out.write("RoleLevel.SuperLevel=0;//超级管理员\r\n");
      out.write("RoleLevel.ProgrammerLevel=6;//程序员\r\n");
      out.write("RoleLevel.PrepareLevel=7;//生产准备组\r\n");
      out.write("RoleLevel.zkLevel=8;//总库管理员\r\n");
      out.write("RoleLevel.fkLevel=9;//分库管理员\r\n");
      out.write("RoleLevel.wcLevel=10;//技术人员\r\n");
      out.write("RoleLevel.mjLevel=11;//模具管理员\r\n");
      out.write("RoleLevel.ybLevel=12;//仪表管理员\r\n");
      out.write("//\r\n");
      out.write("\r\n");
      out.write("function getlengthB(str){\r\n");
      out.write("\treturn str.replace(/[^\\x00-\\xff]/g,\"**\").length;\r\n");
      out.write("}\r\n");
      out.write("function test(){\r\n");
      out.write("\talert(\"test alert\");\r\n");
      out.write("}\r\n");
      out.write("//是否是一般用户\r\n");
      out.write("function isUser(){\r\n");
      out.write("\treturn userlevel == RoleLevel.UserLev ? true : false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//是否是库房管理员\r\n");
      out.write("function isStoreManager(){\r\n");
      out.write("\treturn userlevel == RoleLevel.StoreManagerLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//是否是班组长\r\n");
      out.write("function isTeamLeader(){\r\n");
      out.write("\treturn userlevel == RoleLevel.TeamLeaderLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//是否是领导\r\n");
      out.write("function isBoss(){\r\n");
      out.write("\treturn userlevel == RoleLevel.BossLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//是否是系统管理员\r\n");
      out.write("function isSys(){\r\n");
      out.write("\treturn userlevel == RoleLevel.SysLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//是否是程序员\r\n");
      out.write("function isPro() {\r\n");
      out.write("\treturn userlevel == RoleLevel.ProgrammerLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//是否是超级管理员\r\n");
      out.write("function isSuper(){\r\n");
      out.write("\treturn userlevel == RoleLevel.SuperLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//是否是生产准备组\r\n");
      out.write("function isPre() {\r\n");
      out.write("\treturn userlevel == RoleLevel.PrepareLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("//是否是总库管理员\r\n");
      out.write("function iszk() {\r\n");
      out.write("\treturn userlevel == RoleLevel.zkLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("//是否分库管理员\r\n");
      out.write("function isfk() {\r\n");
      out.write("\treturn userlevel == RoleLevel.fkLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("//是否技术人员\r\n");
      out.write("function iswc() {\r\n");
      out.write("\treturn userlevel == RoleLevel.wcLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("//是否是模具管理员\r\n");
      out.write("function ismj() {\r\n");
      out.write("\treturn userlevel == RoleLevel.mjLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("//是否是仪表管理员\r\n");
      out.write("function isyb() {\r\n");
      out.write("\treturn userlevel == RoleLevel.ybLevel ? true : false;\r\n");
      out.write("}\r\n");
      out.write("/* //set  CookieProvider 对应后面stateId：filetable\r\n");
      out.write("Ext.state.Manager.setProvider(new Ext.state.CookieProvider({\r\n");
      out.write("\texpires: new Date(new Date().getTime()+(1000*60*60*24*365))}\r\n");
      out.write(")); */\r\n");
      out.write("</script>\r\n");

	//不允许浏览器缓存
	response.setHeader("Pragma", "no-cache");
	response.setHeader("Cache-Control", "no-cache");
	response.setHeader("Expires","0");
	session.setMaxInactiveInterval(-1);

      out.write("\r\n");
      out.write("<!-- END Ext -->");
      out.write("\r\n");
      out.write("<title>");
      out.print(GuiStr.SystemTitle);
      out.write("</title>\r\n");
      out.write("</head>\r\n");

String condition="and 1=1 order by isfolder desc,menuname";

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var urlMap=[];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  function get_task(){\t\r\n");
      out.write("    var\tsUrl = '/tsms/web/sms/bscinfmod/task_inf/logic_task_inf.jsp';\r\n");
      out.write("\tvar\tparms = {type:'queryTaskList',userlevel : userlevel,userid:userid};\r\n");
      out.write("\tvar objtp = Ext.util.JSON.decode(callService(sUrl,parms));\r\n");
      out.write("\tvar task_html = objtp.html;\r\n");
      out.write("\treturn task_html;\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("var pop_window = new Ext.ux.ToastWindow();\r\n");
      out.write("  \r\n");
      out.write(" function task_window(){       \r\n");
      out.write("    \r\n");
      out.write("    var task_string = get_task();     \r\n");
      out.write("\tif(!pop_window.isVisible()){\t\r\n");
      out.write("\t   \r\n");
      out.write("\t\tpop_window = new Ext.ux.ToastWindow({\r\n");
      out.write("\t  \tid:'toast_window',\r\n");
      out.write("\t  \ttitle: '<h1 align=\"center\"> 个人待办事项</h1>',\r\n");
      out.write("\t \t html: '',\r\n");
      out.write("\t  \ticonCls: 'error'\r\n");
      out.write("\t\t}); \t\t\r\n");
      out.write("\t  \tpop_window.show(document); \t \r\n");
      out.write("\t  \tExt.getCmp('toast_window').setMessage(task_string);     \r\n");
      out.write("\t}else{\r\n");
      out.write("\t    pop_window.hide(); \t \r\n");
      out.write("\t}\r\n");
      out.write("\t      \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var Tree=Ext.tree;\r\n");
      out.write("//基本信息管理树\r\n");
      out.write("if(isUser()){\r\n");
      out.write("var bscinf_doc =  [{id:'guide', text: '说明',  leaf:true}    \r\n");
      out.write("               // {id:'inventory_control', text: '库存管理' , leaf:true  }\r\n");
      out.write("                ]\r\n");
      out.write("}else if(isBoss()){\r\n");
      out.write("\tvar bscinf_doc =  [{id:'guide', text: '说明',  leaf:true},\r\n");
      out.write("\t                   {id:'component_code', text: '零件编码',  leaf:true},\r\n");
      out.write("\t                   {id:'bom', text: 'bom表', \r\n");
      out.write("\t           children:[{id:'design', text:'设计', leaf:true},\r\n");
      out.write("\t             \t{id:'manufacture', text:'制造', leaf:true},\r\n");
      out.write("\t                {id:'maintainance', text:'维护', leaf:true}]} \r\n");
      out.write("\t                ]\r\n");
      out.write("}else{\r\n");
      out.write("\tvar bscinf_doc =  [{id:'guide', text: '说明',  leaf:true},\r\n");
      out.write("\t                   {id:'component_code', text: '零件编码',  leaf:true},\r\n");
      out.write("\t                   {id:'bom', text: 'bom表', \r\n");
      out.write("\t           children:[{id:'design', text:'设计', leaf:true},\r\n");
      out.write("\t             \t{id:'manufacture', text:'制造', leaf:true},\r\n");
      out.write("\t                {id:'maintainance', text:'维护', leaf:true}]} \r\n");
      out.write("\t                ]\r\n");
      out.write("}\r\n");
      out.write("var bscinf_root = new Ext.tree.AsyncTreeNode({\r\n");
      out.write("\ttext:'按类型',       \r\n");
      out.write("    draggable:false,\r\n");
      out.write("    id:'bscinf_tree_root',\r\n");
      out.write("\texpanded:true,\r\n");
      out.write("    children:bscinf_doc\r\n");
      out.write("});\r\n");
      out.write("var bscinf_panel = new Ext.tree.TreePanel({\r\n");
      out.write("\t//el: 'bscinf_tree',\r\n");
      out.write("\ttitle: '基本信息管理',\r\n");
      out.write("\ticonCls:'files',\r\n");
      out.write("\tanimate: true,\r\n");
      out.write("\tcollapsible: true,\r\n");
      out.write("\trootVisible: false,\r\n");
      out.write("\tautoScroll: true,\r\n");
      out.write("\tborder: false,\r\n");
      out.write("\troot: bscinf_root,\r\n");
      out.write("\tloader: new Tree.TreeLoader({preloadChildren: true,clearOnLoad: false})\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//故障案例库\r\n");
      out.write("if(isUser()){\r\n");
      out.write("\tvar storemgt_doc = [\r\n");
      out.write("{id: 'huizong1', text: '故障汇总', \r\n");
      out.write("\tchildren:[{   id: 'rezhazong',text: '热轧',\r\n");
      out.write("\t\tchildren:[{id:'putrezha',text:'普通热轧机',leaf:true},\r\n");
      out.write("\t\t          {id:'gaosrezha',text:'高速热轧机',leaf:true},\r\n");
      out.write("\t\t          {id:'putsgrezha',text:'普通三辊热轧机',leaf:true}\r\n");
      out.write("\t\t          ,{id:'sgunrezha',text:'S辊（三辊）热轧机',leaf:true}\r\n");
      out.write("\t\t          ,{id:'sgunyxrezha',text:'S辊Y型热轧机',leaf:true},\r\n");
      out.write("\t\t          {id:'sigunrezha',text:'四辊热轧机',leaf:true}]} ,\r\n");
      out.write("\t          {   id: 'shoujuan',text: '收卷',children:[{id:'sgshoujuan',text:'三辊普通收卷机',leaf:true},\r\n");
      out.write("\t         \t\t\t\t\t\t\t\t          {id:'putshoujuan',text:'普通收卷机',leaf:true},\r\n");
      out.write("\t        \t\t\t\t\t\t\t\t          {id:'gaosshoujuan',text:'高速收卷机',leaf:true}\r\n");
      out.write("\t        \t\t\t\t\t\t\t\t          ]},\r\n");
      out.write("\t          {   id: 'fenqie',text: '分切',children:[{id:'putfenqie',text:'普通分切',leaf:true},\r\n");
      out.write("\t\t        \t\t\t\t\t\t\t\t          {id:'gaosfenqie',text:'高速分切',leaf:true}\r\n");
      out.write("\t\t        \t\t\t\t\t\t\t\t          ]},\r\n");
      out.write("\t          {   id: 'qita',text: '其他',children:[{ id:'tangguang',text: '烫光机',leaf:true}, \r\n");
      out.write("\t                                                   { id:'yahua',text: '压花机组',leaf:true},\r\n");
      out.write("\t                                                   { id:'chubu',text: '储布架',leaf:true},\r\n");
      out.write("\t                                                   { id:'bozhou',text: '拨轴机',leaf:true},\r\n");
      out.write("\t                                                   { id:'qslixian',text: '亲水离线',leaf:true},\r\n");
      out.write("\t                                                   { id:'fuhexian',text: '复合线',leaf:true},\r\n");
      out.write("\t                                                   { id:'chenwang',text: '成网机',leaf:true},\r\n");
      out.write("\t                                                   { id:'hongxiang',text: '烘箱',leaf:true},\r\n");
      out.write("\t                                                   { id:'tangpin',text: '烫平机',leaf:true},\r\n");
      out.write("\t                                                   { id:'lenque',text: '冷却机',leaf:true},\r\n");
      out.write("\t                                                   { id:'tuijuan',text: '退卷机',leaf:true},\r\n");
      out.write("\t                                                   { id:'sgwfangjuan',text: '双工位放卷机',leaf:true}]}]},\r\n");
      out.write("{id:'application', text:'在线申请',\r\n");
      out.write("children:[{   id: 'rezha2',text: '申请答疑',leaf:true} ]} \r\n");
      out.write("\t\t\t\t\t\t             \r\n");
      out.write("\t\t\t\t\t\t             ];\r\n");
      out.write("}else{\r\n");
      out.write("\t\tvar storemgt_doc = [{id:'trouble_previous', text:'已有案例',\r\n");
      out.write("\t\t    children:[{   id: 'rezha1',text: '热轧',leaf:true},\r\n");
      out.write("\t\t\t\t        {id: 'shoujuan1', text: '收卷', leaf:true},\r\n");
      out.write("\t\t\t\t\t\t{id: 'fenqie1', text: '分切', leaf:true}]},\r\n");
      out.write("\t\t\t\t\t\t//{id:'huizong',text:'故障汇总',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t{id: 'huizong1', text: '故障汇总', \r\n");
      out.write("\t\t\t\t\t\t\tchildren:[{   id: 'rezhazong',text: '热轧',\r\n");
      out.write("\t\t\t\t\t\t\t\tchildren:[{id:'putrezha',text:'普通热轧机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t\t          {id:'gaosrezha',text:'高速热轧机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t\t          {id:'putsgrezha',text:'普通三辊热轧机',leaf:true}\r\n");
      out.write("\t\t\t\t\t\t\t\t          ,{id:'sgunrezha',text:'S辊（三辊）热轧机',leaf:true}\r\n");
      out.write("\t\t\t\t\t\t\t\t          ,{id:'sgunyxrezha',text:'S辊Y型热轧机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t\t          {id:'sigunrezha',text:'四辊热轧机',leaf:true}]} ,\r\n");
      out.write("\t\t\t\t\t\t\t          {   id: 'shoujuan',text: '收卷',children:[{id:'sgshoujuan',text:'三辊普通收卷机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t         \t\t\t\t\t\t\t\t          {id:'putshoujuan',text:'普通收卷机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t        \t\t\t\t\t\t\t\t          {id:'gaosshoujuan',text:'高速收卷机',leaf:true}\r\n");
      out.write("\t\t\t\t\t\t\t        \t\t\t\t\t\t\t\t          ]},\r\n");
      out.write("\t\t\t\t\t\t\t          {   id: 'fenqie',text: '分切',children:[{id:'putfenqie',text:'普通分切',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t\t        \t\t\t\t\t\t\t\t          {id:'gaosfenqie',text:'高速分切',leaf:true}\r\n");
      out.write("\t\t\t\t\t\t\t\t        \t\t\t\t\t\t\t\t          ]},\r\n");
      out.write("\t\t\t\t\t\t\t          {   id: 'qita',text: '其他',children:[{ id:'tangguang',text: '烫光机',leaf:true}, \r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'yahua',text: '压花机组',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'chubu',text: '储布架',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'bozhou',text: '拨轴机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'qslixian',text: '亲水离线',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'fuhexian',text: '复合线',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'chenwang',text: '成网机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'hongxiang',text: '烘箱',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'tangpin',text: '烫平机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'lenque',text: '冷却机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'tuijuan',text: '退卷机',leaf:true},\r\n");
      out.write("\t\t\t\t\t\t\t                                                   { id:'sgwfangjuan',text: '双工位放卷机',leaf:true}]}]},\r\n");
      out.write("\t                   {id:'application', text:'在线申请',\r\n");
      out.write("\t\t\t\t    children:[{   id: 'rezha2',text: '申请答疑',leaf:true} ]}];\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("    var storemgt_root = new Ext.tree.AsyncTreeNode({\r\n");
      out.write("    \ttext:'',       \r\n");
      out.write("        draggable:false,//可拖动\r\n");
      out.write("        id:'storemgt_tree_root',\r\n");
      out.write("    \texpanded:true,\r\n");
      out.write("        children:storemgt_doc\r\n");
      out.write("    });\r\n");
      out.write("    var storemgt_panel = new Ext.tree.TreePanel({\r\n");
      out.write("    \tid: 'storemgt_tree',\r\n");
      out.write("    \ttitle: '故障案例库',\r\n");
      out.write("    \ticonCls:'assign',\r\n");
      out.write("    \tanimate: true,\r\n");
      out.write("    \tcollapsible: true,\r\n");
      out.write("    \trootVisible: false,\r\n");
      out.write("    \tautoScroll: true,\r\n");
      out.write("    \tborder: false,\r\n");
      out.write("    \troot: storemgt_root,\r\n");
      out.write("    \tloader: new Tree.TreeLoader({preloadChildren: true,clearOnLoad: false})\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("//在线专家诊断\r\n");
      out.write("var gldapp_doc = [{id:'expert_type',text:'在线诊断',leaf:true}/*,\r\n");
      out.write("\t\t\t      {  id:'knowledge',   text:'知识库', leaf:true\r\n");
      out.write("\t\t\t\t  }*/];\r\n");
      out.write("var gldapp_root = new Ext.tree.AsyncTreeNode({\r\n");
      out.write("\ttext:'',       \r\n");
      out.write("    draggable:false,\r\n");
      out.write("    id:'gldapp_tree_root',\r\n");
      out.write("\texpanded:true,\r\n");
      out.write("    children:gldapp_doc\r\n");
      out.write("});\r\n");
      out.write("var gldapp_panel = new Ext.tree.TreePanel({\r\n");
      out.write("\ttitle:'在线专家诊断',  \r\n");
      out.write("    id:'gldapp_manage',\r\n");
      out.write("    iconCls:'teamlead',\r\n");
      out.write("\tanimate: true,\r\n");
      out.write("\tcollapsible: true,\r\n");
      out.write("\trootVisible: false,\r\n");
      out.write("\tautoScroll: true,\r\n");
      out.write("\tborder: false,\r\n");
      out.write("\troot: gldapp_root,\r\n");
      out.write("\tloader: new Tree.TreeLoader({preloadChildren: true,clearOnLoad: false})\r\n");
      out.write("});\r\n");
      out.write("//领导审查模块\r\n");
      out.write("var leader_doc = [{id:'leader_news',text:'领导资讯',leaf:true}/*,\r\n");
      out.write("{  id:'knowledge',   text:'知识库', leaf:true\r\n");
      out.write("}*/];\r\n");
      out.write("var leader_root = new Ext.tree.AsyncTreeNode({\r\n");
      out.write("text:'',       \r\n");
      out.write("draggable:false,\r\n");
      out.write("id:'leader_tree_root',\r\n");
      out.write("expanded:true,\r\n");
      out.write("children:leader_doc\r\n");
      out.write("});\r\n");
      out.write("var leader_panel = new Ext.tree.TreePanel({\r\n");
      out.write("title:'领导审查',  \r\n");
      out.write("id:'leader_manage',\r\n");
      out.write("iconCls:'users',\r\n");
      out.write("animate: true,\r\n");
      out.write("collapsible: true,\r\n");
      out.write("rootVisible: false,\r\n");
      out.write("autoScroll: true,\r\n");
      out.write("border: false,\r\n");
      out.write("root: leader_root,\r\n");
      out.write("loader: new Tree.TreeLoader({preloadChildren: true,clearOnLoad: false})\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//个人信息管理树\r\n");
      out.write("var usrinf_doc_leader = [{\r\n");
      out.write("\tid:'usrinf_m_leader', \r\n");
      out.write("\ttext:'个人信息管理',\r\n");
      out.write("\tchildren:[\r\n");
      out.write("\t\t  \t\t{\r\n");
      out.write("\t\t\t\t\tid:'usrinf_check_leader',\r\n");
      out.write("\t\t\t\t\ttext:'个人信息查看',\r\n");
      out.write("\t\t\t\t\tleaf:true\r\n");
      out.write("\t\t\t\t},{\r\n");
      out.write("\t\t\t\t\tid:'usrinf_pwdedit_leader',\r\n");
      out.write("\t\t\t\t\ttext:'个人密码修改',\r\n");
      out.write("\t\t\t\t\tleaf:true\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t]\r\n");
      out.write("\t}];\r\n");
      out.write("var usrinf_root_leader = new Ext.tree.AsyncTreeNode({\r\n");
      out.write("\ttext:'',       \r\n");
      out.write("    draggable:false,\r\n");
      out.write("    id:'usrinf_tree_root_leader',\r\n");
      out.write("\texpanded:true,\r\n");
      out.write("    children:usrinf_doc_leader\r\n");
      out.write("});\r\n");
      out.write(" var usrinf_panel_leader = new Ext.tree.TreePanel({\r\n");
      out.write("\ttitle:'个人信息管理',  \r\n");
      out.write("    id:'usrinf_manage_leader',\r\n");
      out.write("    iconCls:'usrinf',\r\n");
      out.write("\tanimate: true,\r\n");
      out.write("\tcollapsible: true,\r\n");
      out.write("\trootVisible: false,\r\n");
      out.write("\tautoScroll: true,\r\n");
      out.write("\tborder: false,\r\n");
      out.write("\troot: usrinf_root_leader,\r\n");
      out.write("\tloader: new Tree.TreeLoader({preloadChildren: true,clearOnLoad: false})\r\n");
      out.write("});  \r\n");
      out.write("\r\n");
      out.write("//用户管理树\r\n");
      out.write("var usrmgt_doc = [{id:'usrmgt_add', text:'添加新用户', leaf:true},\r\n");
      out.write("                  {id:'usrmgt_mod', text:'修改/删除用户信息', leaf:true}]\r\n");
      out.write("var usrmgt_root = new Ext.tree.AsyncTreeNode({\r\n");
      out.write("\ttext:'',       \r\n");
      out.write("    draggable:false,\r\n");
      out.write("    id:'usrmgt_tree_root',\r\n");
      out.write("\texpanded:true,\r\n");
      out.write("    children:usrmgt_doc\r\n");
      out.write("});\r\n");
      out.write("var usrmgt_panel = new Ext.tree.TreePanel({\r\n");
      out.write("\ttitle:'用户管理', \r\n");
      out.write("    id:'usrmgt_manage',\r\n");
      out.write("    iconCls:'group',\r\n");
      out.write("\tanimate: true,\r\n");
      out.write("\tcollapsible: true,\r\n");
      out.write("\tcollapsed: false,\r\n");
      out.write("\trootVisible: false,\r\n");
      out.write("\tautoScroll: true,\r\n");
      out.write("\tborder: false,\r\n");
      out.write("\troot: usrmgt_root,\r\n");
      out.write("\tloader: new Tree.TreeLoader({preloadChildren: true,clearOnLoad: false})\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//基本信息模块\r\n");
      out.write("urlMap[\"guide\"]=\"web/sms/bscinfmod/gen_tool/sum.jsp\";\r\n");
      out.write("urlMap[\"component_code\"]=\"web/sms/bscinfmod/cutter/cutter.jsp\";\r\n");
      out.write("//urlMap[\"inventory_control\"]=\"web/sms/storestatmod/storestatmod_c/tabpan.jsp\";//库存管理\r\n");
      out.write("urlMap[\"design\"]=\"web/sms/storemgtmod/material/material_out.jsp\";\r\n");
      out.write("urlMap[\"manufacture\"]=\"web/sms/storemgtmod/manufacture/manufacture.jsp\";\r\n");
      out.write("urlMap[\"maintainance\"]=\"web/sms/storemgtmod/matain/matain.jsp\";\r\n");
      out.write("//故障案例库\r\n");
      out.write("urlMap[\"rezha1\"]=\"web/sms/storemgtmod/m_check/m_delete.jsp\";\r\n");
      out.write("urlMap[\"shoujuan1\"]=\"web/sms/storemgtmod/shoujuan/shoujuan.jsp\";\r\n");
      out.write("urlMap[\"fenqie1\"]=\"web/sms/storemgtmod/fenqie/fenqie.jsp\";\r\n");
      out.write("//urlMap[\"huizong\"]=\"web/sms/storemgtmod/huizong/huizong.jsp\";//故障汇总\r\n");
      out.write("//分切\r\n");
      out.write("urlMap[\"putrezha\"]=\"web/sms/storemgtmod/huizong/putrezha.jsp\";\r\n");
      out.write("urlMap[\"gaosrezha\"]=\"web/sms/storemgtmod/huizong/gaosrezha.jsp\";\r\n");
      out.write("urlMap[\"putsgrezha\"]=\"web/sms/storemgtmod/huizong/putsgrezha.jsp\";\r\n");
      out.write("urlMap[\"sgunrezha\"]=\"web/sms/storemgtmod/huizong/sgunrezha.jsp\";\r\n");
      out.write("urlMap[\"sgunyxrezha\"]=\"web/sms/storemgtmod/huizong/sgunyxrezha.jsp\";\r\n");
      out.write("urlMap[\"sigunrezha\"]=\"web/sms/storemgtmod/huizong/sigunrezha.jsp\";\r\n");
      out.write("//收卷\r\n");
      out.write("urlMap[\"sgshoujuan\"]=\"web/sms/storemgtmod/huizong/sgshoujuan.jsp\";\r\n");
      out.write("urlMap[\"putshoujuan\"]=\"web/sms/storemgtmod/huizong/putshoujuan.jsp\";\r\n");
      out.write("urlMap[\"gaosshoujuan\"]=\"web/sms/storemgtmod/huizong/gaosshoujuan.jsp\";\r\n");
      out.write("//分切\r\n");
      out.write("urlMap[\"putfenqie\"]=\"web/sms/storemgtmod/huizong/putfenqie.jsp\";\r\n");
      out.write("urlMap[\"gaosfenqie\"]=\"web/sms/storemgtmod/huizong/gaosfenqie.jsp\";\r\n");
      out.write("//其他\r\n");
      out.write("urlMap[\"tangguang\"]=\"web/sms/storemgtmod/huizong/tangguang.jsp\";\r\n");
      out.write("urlMap[\"yahua\"]=\"web/sms/storemgtmod/huizong/yahua.jsp\";\r\n");
      out.write("urlMap[\"chubu\"]=\"web/sms/storemgtmod/huizong/chubu.jsp\";\r\n");
      out.write("urlMap[\"bozhou\"]=\"web/sms/storemgtmod/huizong/bozhou.jsp\";\r\n");
      out.write("urlMap[\"qslixian\"]=\"web/sms/storemgtmod/huizong/qslixian.jsp\";\r\n");
      out.write("urlMap[\"fuhexian\"]=\"web/sms/storemgtmod/huizong/fuhexian.jsp\";\r\n");
      out.write("urlMap[\"chenwang\"]=\"web/sms/storemgtmod/huizong/chenwang.jsp\";\r\n");
      out.write("urlMap[\"hongxiang\"]=\"web/sms/storemgtmod/huizong/hongxiang.jsp\";\r\n");
      out.write("urlMap[\"tangpin\"]=\"web/sms/storemgtmod/huizong/tangpin.jsp\";\r\n");
      out.write("urlMap[\"lenque\"]=\"web/sms/storemgtmod/huizong/lenque.jsp\";\r\n");
      out.write("urlMap[\"tuijuan\"]=\"web/sms/storemgtmod/huizong/tuijuan.jsp\";\r\n");
      out.write("urlMap[\"sgwfangjuan\"]=\"web/sms/storemgtmod/huizong/sgwfangjuan.jsp\";\r\n");
      out.write("\r\n");
      out.write("urlMap[\"rezha2\"]=\"web/sms/storemgtmod/cut_tool/pa_c_tab.jsp\";\r\n");
      out.write("\r\n");
      out.write("//在线专家诊断\r\n");
      out.write("urlMap[\"expert_type\"] =\"web/sms/ldappmod/check/entrycheck.jsp\";\r\n");
      out.write("//\r\n");
      out.write("urlMap[\"leader_news\"]=\"web/sms/storestatmod/storestatemod_material/material_warn.jsp\";\r\n");
      out.write("//\r\n");
      out.write("urlMap[\"usrinf_pwdedit_leader\"]=\"web/sms/usrinfmod/usrinfmod/usreditpwd.jsp\";\r\n");
      out.write("urlMap[\"usrinf_check_leader\"]=\"web/sms/usrinfmod/usrinfmod/usrinf_check.jsp\";\r\n");
      out.write("\r\n");
      out.write("//用户管理模块\r\n");
      out.write("urlMap[\"usrmgt_add\"]=\"web/sms/usrmgtmod/usradd.jsp\";\r\n");
      out.write("urlMap[\"usrmgt_mod\"]=\"web/sms/usrmgtmod/usrmod.jsp\";\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"menu\"></div>\r\n");
      out.write("<div id=\"north\">\r\n");
      out.write("\t<table id=\"header\" style=\"display:none\" width=\"100%\" height=\"100%\" background=\"/tsms/web/inc/resources/images/custom/headback.jpg\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\"><tr><td width=450 background=\"/tsms/web/inc/resources/images/custom/head.jpg\">&nbsp;</td><td valign=\"center\" align=\"right\"><span id=\"loginInf\" style=\"font-size:12px;color:#ffffff\">&nbsp;</span><span><a href=\"javascript:task_window()\" ><font style=\"font-size:12px;color:#ffffff\"><img border=0 src=\"/tsms/web/inc/resources/images/custom/information.gif\" valign=center>个人待办事项</font></a></span><img id=\"roleimages\" border=0 src=\"/tsms/web/inc/resources/images/custom/folder_user.png\" valign=center><a href=\"javascript:showrole()\" id=\"rolechoose\">&nbsp;<font style=\"font-size:12px;color:#ffffff\">角色选择</font></a><a href=\"login/logout.jsp\"><font style=\"font-size:12px;color:#ffffff\"><img border=0 src=\"/tsms/web/inc/resources/images/custom/logout.gif\" valign=center>退出系统</font></a>&nbsp;&nbsp;<span id=\"help\" style=\"font-size:12px;color:#ffffff\">&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;</td></tr></table>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"center\" >\r\n");
      out.write("\t<iframe id=\"mainFrame\" name=\"mainFrame\" class=\"mainFrame\" width=\"100%\" height=\"100%\" frameborder=\"0\" src=\"\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"silu\"><button id=\"taskbtn\" onclick=\"show_pop()\" style=\"display:none\">显示任务</button></div> \r\n");
      out.write("<div id=\"winpop\"  class = \"scrollbar\" style=\"border:1px solid #9EB7F9;\" onMouseOut=\"hideContent();\"></div> \r\n");
      out.write("<div  id=\"content\" class = \"content\" style=\"border:0px solid #9EB7F9;display:none\"></div> \r\n");
      out.write("\r\n");
      out.write("<div id=\"bscinf_tree\" style=\"overflow:auto;height:100%;width:100%;\"></div>\r\n");
      out.write("<div id=\"storemgt_tree\" style=\"overflow:auto;height:100%;width:100%;\"></div>\r\n");
      out.write("<div id=\"gldapp_tree\" style=\"overflow:auto;height:100%;width:100%;\"></div>\r\n");
      out.write("<div id=\"Idapp_tree\" style=\"overflow:auto;height:100%;width:100%;\"></div>\r\n");
      out.write("<div id=\"storestat_tree\" style=\"overflow:auto;height:100%;width:100%;\"></div>\r\n");
      out.write("<div id=\"usrinf_tree\" style=\"overflow:auto;height:100%;width:100%;\"></div>\r\n");
      out.write("<div id=\"usrmgt_tree\" style=\"overflow:auto;height:100%;width:100%;\"></div>\r\n");
      out.write("<div id=\"divinput\" style=\"position:absolute;top:750px;left:350px;display:none;z-index:100\">\r\n");
      out.write("<INPUT TYPE=\"text\" NAME=\"divput\" id=\"divput\" class='rename-input'><input type=\"button\" value=\"确定\" class=\"rename-button\" onclick=\"rename()\"><input type=\"button\" value=\"取消\" class=\"rename-button\" onclick=\"cancelRename()\">\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/tsms/index.js\"></script>\r\n");
      out.write("<body oncontextmenu=\"return false\">\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
